# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build artifact with Maven

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven

      - name: Build with Maven
        run: mvn -B -U package

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: idporten-log-event/target/*.jar