name: Maven build

on:
  push:
    paths-ignore:
      - '.github/**'

jobs:
  call-workflow-maven-build:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build-lib.yml@main
    with:
      java-version: 17
      sbom-path: ./log-event/target/
    secrets: inherit
