on: [ push ]

jobs:
  call-workflow-maven-build:
    uses: local-maven-build-lib.yml@main
    with:
      java-version: 8
      sbom-path: ./log-event/target/
    secrets:
      maven-user: ${{ secrets.MAVEN_USER }}
      maven-password: ${{ secrets.MAVEN_PASSWORD }}