name: Release to Artifactory

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "0.0.1"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "0.0.2-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven

      - name: Set up Maven settings
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
            "id": "digdir-artifactory",
            "username": "${{ secrets.MAVEN_USER }}",
            "password": "${{ secrets.MAVEN_PASSWORD }}"
            }]

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Maven Release
        run: mvn release:prepare release:perform -X -B -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.MAVEN_USER }}
          CI_DEPLOY_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
