name: Release to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "0.0.1"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "0.0.2-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@v1
        with:
          maven-args: "clean install"

      - name: Release
        uses: qcastel/github-actions-maven-release@v1
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
        with:
          maven-project-folder: "idporten-log-event/"
          maven-repo-server-id: github
          maven-repo-server-username: ${{ secrets.MAVEN_USER }}
          maven-repo-server-password: ${{ secrets.MAVEN_PASSWORD }}
          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          git-release-bot-name: "github-action"
          git-release-bot-email: "actions@github.com"
          maven-args: "-DskipTests"