name: Release to Artifactory

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "0.0.1"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "0.0.1-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven

      - name: Set up Maven settings
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
            "id": "digdir-artifactory",
            "username": "${{ secrets.MAVEN_USER }}",
            "password": "${{ secrets.MAVEN_PASSWORD }}"
            }]

      - name: Maven Release
        run: mvn release:prepare release:perform -B -s .maven_settings.xml -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
