name: Release to GitHub Packages

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "0.0.1"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "0.0.2-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven
      #          server-id: github
      #          settings-path: ${{ github.workspace }}


      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Deploy to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${GITHUB_ACTOR}</username><password>\${env.GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          REPO="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}"
          mvn release:prepare -B -X -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}
          mvn -B deploy -DaltDeploymentRepository="${REPO}"
        #          mvn versions:set -B -DnewVersion="${{ github.event.inputs.releaseVersion }}"
